# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
- env:
  - CGO_ENABLED=0
  binary: terraform-provider-sumologic
  goos:
  - darwin
  - freebsd
  - linux
  - openbsd
  - solaris
  - windows
  goarch:
  - 386
  - amd64
  - arm
  ignore:
  - goos: darwin
    goarch: 386
  - goos: darwin
    goarch: arm
archive:
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  replacements:
    darwin: macOS
    linux: Linux
    windows: Windows
    freebsd: Freebsd
    386: 32-bit
    amd64: 64-bit
    solaris: solaris
  format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
